<a href="https://colab.research.google.com/github/jarwow/Bluemix_NLC_Nodejs/blob/master/ann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
  
import numpy as np


# Times to run
epoch = 10000


# There are 2 inputs
inputLayerSize = 2


# NN nodes
hiddenLayerSize = 5


# Only one output
outputLayerSize = 1


L=0.1


# There are 2 inputs for XOR
X = np.array( [ [0,0], [0,1], [1,0], [1,1] ] )


# The truth table of XOR
# ANN just can learn from truly examples!!!
#     (adjust the weight and bias to make output is getting close to target by input)
Y = np.array( [ [0], [1], [1], [0] ] )


def sigmod(x):
    return 1 / (1 + np.exp(-x))


def sigmoid_deriv(x):
	return x * (1 - x)
	
Wh = np.random.uniform(size=(inputLayerSize, hiddenLayerSize))
Wz = np.random.uniform(size=(hiddenLayerSize, outputLayerSize))


for i in range(epoch):
 H = sigmod(np.dot(X, Wh))
 Z = np.dot(H, Wz)
 E = Y - Z
 dZ = E * L
 Wz += H.T.dot(dZ)
 dH = dZ.dot(Wz.T) * sigmoid_deriv(H)
 Wh +=  X.T.dot(dH)


print("**************** error ****************") 
print(E)
print("***************** output **************") 
print(Z)   
print("*************** weights ***************") 
print("input to hidden layer weights: ")     
print(Wh)
print("hidden to output layer weights: ")
print(Wz)


**************** error ****************
[[-3.10862447e-15]
 [ 3.99680289e-15]
 [ 3.77475828e-15]
 [-6.21724894e-15]]
***************** output **************
[[3.10862447e-15]
 [1.00000000e+00]
 [1.00000000e+00]
 [6.21724894e-15]]
*************** weights ***************
input to hidden layer weights: 
[[ 3.80494256 -1.18335007  1.27881706 -0.84758346  0.01640419]
 [ 4.00178074 -0.13680946  0.11641183 -0.23826213  1.46013726]]
hidden to output layer weights: 
[[ 4.44494683]
 [ 0.95104461]
 [-2.6871747 ]
 [ 0.50730827]
 [-3.21612501]]
